# -*- coding: utf-8 -*-
"""Level 2: Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PpMYimclGpTKF2xjmvOV8xOlEPPl1XDK

# Level 2: Task 1 - Restaurant Ratings

### Import Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

"""### Load the Dataset"""

file_path = "/content/Dataset .csv"
data = pd.read_csv(file_path)

print("Dataset:")
print(data.head())

"""# **Analyze Rating Distribution**"""

plt.figure(figsize=(10, 6))
sns.histplot(data['Aggregate rating'], bins=10, kde=True, color='blue')
plt.title('Distribution of Aggregate Ratings', fontsize=16)
plt.xlabel('Ratings', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.show()

"""### Most Common Rating Range"""

bins = np.arange(0, 5, 21)
data['Rating_Range'] = pd.cut(data['Aggregate rating'], bins=bins)

bins = np.linspace(0, 5, 21)
data['Rating_Range'] = pd.cut(data['Aggregate rating'], bins=bins)

rating_range_counts = data['Rating_Range'].value_counts().sort_index()
print("\nMost Common Rating Range:")
print(rating_range_counts.idxmax())

"""## Calculate Average Votes"""

average_votes = data['Votes'].mean()
print(f"\nAverage Number of Votes Received by Restaurants: {average_votes:.2f}")

"""# **Visualizations**"""

rating_range_counts.plot(kind='bar', color='red', figsize=(10, 6))
plt.title('Most Common Rating Range', fontsize=16)
plt.xlabel('Rating Range', fontsize=12)
plt.ylabel('Number of Restaurants', fontsize=12)
plt.xticks(rotation=45)
plt.show()

"""Pie Chart for Rating Ranges"""

data['Rating_Range'].value_counts().plot(kind='pie', autopct='%1.2f%%', figsize=(20, 20), startangle=140)
plt.title('Rating Distribution')
plt.show()

"""# Final Result"""

output_df = pd.DataFrame({
    'Rating Range': rating_range_counts.index.astype(str),
    'Count': rating_range_counts.values
})
output_df.to_csv('Restaurant_Rating_Analysis.csv', index=False)
print("Results saved to 'Restaurant_Rating_Analysis.csv'")

from google.colab import files
files.download('Restaurant_Rating_Analysis.csv')