# -*- coding: utf-8 -*-
"""Level 1-Task 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKjdk7jfJo6hwNAXh8sp_QK-FAYFk7O_

# Task 4: Online Delivery Analysis

## Import Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt

"""##Load the dataset"""

file_path = '/content/Dataset .csv'
data = pd.read_csv(file_path)

print(data.head())

"""# Online Delivery Analysis"""

online_delivery_counts = data['Has Online delivery'].value_counts()
total_restaurants = len(data)

# percentages
online_delivery_percentage = (online_delivery_counts / total_restaurants) * 100
print("\nPercentage of Restaurants Offering Online Delivery:")
print(online_delivery_percentage)

avg_rating_online_delivery = data.groupby('Has Online delivery')['Aggregate rating'].mean()
print("\nAverage Ratings by Online Delivery Availability:")
print(avg_rating_online_delivery)

"""## Visualization"""

online_delivery_counts.plot(kind='bar', color='blue', figsize=(8, 5))
plt.title('Percentage of Restaurants Offering Online Delivery')
plt.xlabel('Has Online Delivery')
plt.ylabel('Number of Restaurants')
plt.xticks(rotation=0)
plt.show()

"""**Average Rating Comparison**"""

avg_rating_online_delivery.plot(kind='bar', color=['orange', 'blue'], figsize=(8, 5))
plt.title('Average Ratings: With and Without Online Delivery')
plt.xlabel('Online Delivery')
plt.ylabel('Average Rating')
plt.xticks(rotation=0)
plt.show()

"""# Save the Result"""

online_delivery_summary = pd.DataFrame({
    'Online Delivery': online_delivery_counts.index,
    'Count': online_delivery_counts.values,
    'Percentage': online_delivery_percentage.values,
    'Average Rating': avg_rating_online_delivery.values
})
online_delivery_summary.to_csv('Online_Delivery_Analysis.csv', index=False)
print("Results saved to 'Online_Delivery_Analysis.csv'")

from google.colab import files
files.download('Online_Delivery_Analysis.csv')

