# -*- coding: utf-8 -*-
"""Level 2: Task 4ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15K75A0EIN5UxEExi371ugfhlPUDpUyo-

# Level 2: Task 4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_path = '/content/Dataset .csv'
data = pd.read_csv(file_path)

print(data.head())
print(data.info())

data.isnull().sum()

restaurant_chains = data['Restaurant Name'].unique()
print(f"Restaurant Chains: {restaurant_chains}")

avg_ratings = data.groupby('Restaurant Name')['Aggregate rating'].mean().reset_index()

avg_ratings_sorted = avg_ratings.sort_values(by='Aggregate rating', ascending=False)
print(avg_ratings_sorted)

top_10_ratings = avg_ratings_sorted.head(10)

plt.figure(figsize=(10, 6))
plt.bar(top_10_ratings['Restaurant Name'], top_10_ratings['Aggregate rating'], color='skyblue')
plt.xlabel('Restaurant Name')
plt.ylabel('Average Rating')
plt.title('Top 10 Restaurant Chains by Average Rating')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

popularity = data.groupby('Restaurant Name')['Aggregate rating'].sum().reset_index()

popularity_sorted = popularity.sort_values(by='Aggregate rating', ascending=False)
print(popularity_sorted)

plt.figure(figsize=(10, 6))
popularity_sorted = popularity_sorted.head(20)  # Top 20 restaurant chains
# Pass the specific columns as x and y instead of .values and .index
sns.barplot(x='Aggregate rating', y='Restaurant Name', data=popularity_sorted, palette='Blues')
plt.title('Top 20 Popular Restaurant Chains by Frequency')
plt.xlabel('Frequency')
plt.ylabel('Restaurant Chain')
plt.show()

restaurant_chains_df = pd.DataFrame(restaurant_chains, columns=['Restaurant Name'])
restaurant_chains_df.to_csv('Restaurant_Chains_Analysis.csv', header=True, index=False)

from google.colab import files
files.download('Restaurant_Chains_Analysis.csv')