# -*- coding: utf-8 -*-
"""Level 1: Task 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wmzf3xICaGzKYU_JvjekoMJUCRJwm3PL

# Task 3: Price Range Distribution

## Import Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt

file_path = '/content/Dataset .csv'
data = pd.read_csv(file_path)

"""## Print the Dataset"""

print(data.head())

"""# Analyze Price Range Distribution"""

price_range_counts = data['Price range'].value_counts()
print(price_range_counts)

total_restaurants = len(data)
price_range_percentage = (price_range_counts / total_restaurants) * 100
print("\nPercentage of Restaurants in Each Price Range:")
print(price_range_percentage)

"""## Visualization Price Range Distribution"""

price_range_counts.plot(kind='bar', color='skyblue', figsize=(10, 6))
plt.title('Price Range Distribution')
plt.xlabel('Price Range')
plt.ylabel('Number of Restaurants')
plt.xticks(rotation=45)
plt.show()

price_range_counts.plot(kind='pie', autopct='%1.1f%%', figsize=(8, 8), startangle=140, colors=['Red', 'orange', 'lightgreen','Lightblue'])
plt.title('Percentage of Restaurants by Price Range')
plt.show()

"""# Save the Result"""

price_range_df = pd.DataFrame({
    'Price Range': price_range_counts.index,
    'Count': price_range_counts.values,
    'Percentage': price_range_percentage.values
})
price_range_df.to_csv('Price_Range_Distribution.csv', index=False)
print("Results saved to 'Price_Range_Distribution.csv'")

from google.colab import files
files.download('Price_Range_Distribution.csv')

