# -*- coding: utf-8 -*-
"""Level 2:Task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iWe5a4LNfyfwolaxqCmAerc-SN7lfLyR

# Level 2: Task 3

## Importing  Relevant Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""### Load Dataset"""

file_path = '/content/Dataset .csv'
data = pd.read_csv(file_path)

print(data.head())
print(data.info())

"""#Plot Locations on an Map"""

import folium
from folium.plugins import MarkerCluster

"""## Calculate the center of the map"""

avg_lat = data['Latitude'].mean()
avg_lon = data['Longitude'].mean()

map_restaurants = folium.Map(location=[avg_lat, avg_lon], zoom_start=12)

marker_cluster = MarkerCluster().add_to(map_restaurants)

for _, row in data.iterrows():
    folium.Marker(location=[row['Latitude'], row['Longitude']],
                  popup=row['Restaurant Name']).add_to(marker_cluster)

map_restaurants.save('Interactive_Restaurant_Map.html')
print("Interactive map saved as 'Interactive_Restaurant_Map.html'")

from google.colab import files
files.download('Interactive_Restaurant_Map.html')

"""# Perform Clustering with DBSCAN"""

from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

coordinates = data[['Latitude', 'Longitude']].dropna()
scaler = StandardScaler()
scaled_coordinates = scaler.fit_transform(coordinates)

dbscan = DBSCAN(eps=0.1, min_samples=5)
data['Cluster'] = dbscan.fit_predict(scaled_coordinates)

"""## Visualization of Clusters"""

plt.figure(figsize=(10, 8))
plt.scatter(data['Longitude'], data['Latitude'], c=data['Cluster'], cmap='tab10', alpha=0.7)
plt.colorbar(label='Cluster')
plt.title('Clusters of Restaurants')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.show()

data.to_csv('Restaurant_Clusters.csv', index=False)
print("Clustered data saved as 'Restaurant_Clusters.csv'")

"""# Result"""

from google.colab import files
files.download('Restaurant_Clusters.csv')